### ISSUE TITLE
Depdendency issue

### ISSUE THREAD

**Issue by michaelmior** [LouisonGitzinger/webviewAnalyzer#1]
I run into the following dependency problem when trying to compile.

```
[ERROR] Failed to execute goal on project webviewAnalyzer: Could not resolve dependencies for project webviewAnalyzer:webviewAnalyzer:jar:1.0-SNAPSHOT: Failed to collect dependencies at axml:com.axml:jar:2.0: Failed to read artifact descriptor for axml:com.axml:jar:2.0: Could not transfer artifact axml:com.axml:pom:2.0 from/to soot-snapshot (http://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): Failed to transfer file: http://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/axml/com.axml/2.0/com.axml-2.0.pom. Return code is: 400 , ReasonPhrase:Bad Request. -> [Help 1]
```

**Comment by LouisonGitzinger** [comment]
Hi, sorry for the wait.
To begin, you have to know that this program is still in development, so major updates can occur at any time.

the axml dependency is a dependency I use to run the soot framework. However, this dependency isn't available on the online maven repo, so you have to add it to your local repo.
You can find it here : [axml-2.0.jar](https://github.com/secure-software-engineering/soot-infoflow-android/raw/develop/lib/axml-2.0.jar)

There are other dependencies that are required in order to compile the program, they are all available on this page : 
https://github.com/secure-software-engineering/soot-infoflow-android/wiki

**Comment by michaelmior** [comment]
No problem. Thanks for the pointers!
